# =============================================================
# GitHub Actions Security Analysis with zizmor 🌈
# =============================================================

name: GitHub Actions Security Analysis with zizmor 🌈

on:
  push:
    branches: ['main']
    paths:
      - '.github/workflows/**'
  pull_request:
    branches: ['main']

env:
  NODE_VERSION: 24
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  zizmor:
    name: Run zizmor 🌈
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      security-events: write
      contents: read
      actions: read
    steps:
      - name: Harden Runner 🛡️
        uses: step-security/harden-runner@b09bb98e06d4d774595224525879c09bc6e98c40 # v2.20.1
        with:
          egress-policy: audit

      - name: Checkout repository 📥
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          fetch-depth: 1

      - name: Run zizmor 🌈
        uses: zizmorcore/zizmor-action@3dc1ecc9bcb9e94e9b2c709687979e1298497054 # v0.6.2
